/*

  HashGarten 0.21.0 - a GUI to calculate and verify hashes, powered by Jacksum
  Copyright (c) 2022-2026 Dipl.-Inf. (FH) Johann N. Löfflmann,
  All Rights Reserved, <https://jacksum.net>.

  This program is free software: you can redistribute it and/or modify it under
  the terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.

  This program is distributed in the hope that it will be useful, but WITHOUT
  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
  details.

  You should have received a copy of the GNU General Public License along with
  this program. If not, see <https://www.gnu.org/licenses/>.

 */
package net.jacksum.gui.dialogs;

import java.io.IOException;
import net.jacksum.actions.info.help.Help;
import net.jacksum.actions.info.help.NothingFoundException;
import net.jacksum.gui.interfaces.DialogInterface;


/**
 *
 * @author Johann
 */
public class HelpDialog extends javax.swing.JDialog {

    
    public HelpDialog(DialogInterface dialogInterface, boolean modal) {
        super(dialogInterface.getFrame(), modal);
        init();
    }

    /**
     * Creates a help dialog that belongs to another dialog, e.g. to a modal one, which would
     * block a help dialog that belongs to the main frame.
     *
     * @param owner the dialog the help dialog belongs to
     * @param modal whether the dialog should be modal
     */
    public HelpDialog(java.awt.Dialog owner, boolean modal) {
        super(owner, modal ? DEFAULT_MODALITY_TYPE : ModalityType.MODELESS);
        init();
    }

    private void init() {
        initComponents();
        helpTextArea.putClientProperty( "FlatLaf.style", "font: $monospaced.font" );
        net.jacksum.gui.util.SwingUtils.installCopyContextMenu(helpTextArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        helpPanel = new javax.swing.JPanel();
        helpScrollPane = new javax.swing.JScrollPane();
        helpTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Help");

        cancelButton.setText("Close");
        cancelButton.setToolTipText("Close this window");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        helpTextArea.setEditable(false);
        helpTextArea.setColumns(20);
        helpTextArea.setRows(5);
        helpTextArea.setToolTipText("Help text from the Jacksum manpage");
        helpScrollPane.setViewportView(helpTextArea);

        javax.swing.GroupLayout helpPanelLayout = new javax.swing.GroupLayout(helpPanel);
        helpPanel.setLayout(helpPanelLayout);
        helpPanelLayout.setHorizontalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpScrollPane)
                .addContainerGap())
        );
        helpPanelLayout.setVerticalGroup(
            helpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(helpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addGap(0, 557, Short.MAX_VALUE)
                        .addComponent(cancelButton))
                    .addComponent(helpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(helpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    public void searchHelp(String text) throws NothingFoundException, IOException {
        searchHelp(text, false);
    }

    public void searchHelp(String text, boolean strict) throws NothingFoundException, IOException {
        ensureMonospacedFont();
        statusLabel.setText("");
        helpTextArea.setText(Help.searchHelp("en", text, strict));
        helpTextArea.setCaretPosition(0);
        fitWidthToText();
    }
    
    public void searchHelp(boolean strict, String... texte) throws NothingFoundException, IOException {
        StringBuilder sb = new StringBuilder();
        for (String s : texte) {
            sb.append(Help.searchHelp("en", s, strict));
        }
        ensureMonospacedFont();
        statusLabel.setText("");
        helpTextArea.setText(sb.toString());
        helpTextArea.setCaretPosition(0);
        fitWidthToText();
    }

    /**
     * Shows the dialog centered over a window, so that it doesn't appear on another screen than
     * the one the user is looking at. That happens if it is not visible yet, or if it is on
     * another screen than the window (e.g. the window has been moved since). A dialog that is
     * already open on the same screen stays where the user has put it.
     *
     * @param owner the window to center over, usually the main window
     */
    public void showOver(java.awt.Window owner) {
        java.awt.GraphicsConfiguration screen = screenOf(owner);
        if (!isVisible() || !screen.getBounds().contains(centerOf(this))) {
            // computed rather than by setLocationRelativeTo(), which relies on the screen that
            // AWT has assigned to the owner, and that lags behind after the owner has been
            // shown or moved, so the dialog was put onto the wrong screen
            java.awt.Rectangle ownerBounds = owner.getBounds();
            java.awt.Rectangle usable = usableBounds(screen);
            int x = ownerBounds.x + (ownerBounds.width - getWidth()) / 2;
            int y = ownerBounds.y + (ownerBounds.height - getHeight()) / 2;
            // keep it on the screen, e.g. if the owner is partly off the screen
            x = Math.max(usable.x, Math.min(x, usable.x + usable.width - getWidth()));
            y = Math.max(usable.y, Math.min(y, usable.y + usable.height - getHeight()));
            setLocation(x, y);
        }
        setVisible(true);
    }

    private static java.awt.Point centerOf(java.awt.Window window) {
        java.awt.Rectangle bounds = window.getBounds();
        return new java.awt.Point((int) bounds.getCenterX(), (int) bounds.getCenterY());
    }

    // the screen that contains the center of the window, according to its actual position
    private static java.awt.GraphicsConfiguration screenOf(java.awt.Window window) {
        java.awt.Point center = centerOf(window);
        for (java.awt.GraphicsDevice device
                : java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getScreenDevices()) {
            java.awt.GraphicsConfiguration gc = device.getDefaultConfiguration();
            if (gc.getBounds().contains(center)) {
                return gc;
            }
        }
        return window.getGraphicsConfiguration();
    }

    // the bounds of a screen without the menu bar, the dock resp. the task bar
    private static java.awt.Rectangle usableBounds(java.awt.GraphicsConfiguration gc) {
        java.awt.Rectangle bounds = gc.getBounds();
        java.awt.Insets insets = java.awt.Toolkit.getDefaultToolkit().getScreenInsets(gc);
        return new java.awt.Rectangle(bounds.x + insets.left, bounds.y + insets.top,
                bounds.width - insets.left - insets.right, bounds.height - insets.top - insets.bottom);
    }

    /**
     * Widens the dialog so that the longest line of the text fits without scrolling horizontally.
     * It is never narrowed, so the width of the layout is the minimum, and a width that the user
     * has chosen is kept. It is never wider than the screen either; the rest can be scrolled then.
     *
     * The viewer of files doesn't call it, because a file may have lines of any length.
     */
    public void fitWidthToText() {
        // lay out the new text first, so that the vertical scroll bar is there if it is needed;
        // the height doesn't change, so it stays like that
        validate();
        // the preferred width of the text area is its longest line, plus its insets and the caret;
        // everything around the viewport (borders, gaps, scroll bar) is taken from the layout
        int needed = getWidth() - helpScrollPane.getViewport().getWidth()
                + helpTextArea.getPreferredSize().width;
        if (needed <= getWidth()) {
            return;
        }
        java.awt.GraphicsConfiguration gc = getGraphicsConfiguration();
        java.awt.Rectangle screen = gc.getBounds();
        java.awt.Insets screenInsets = getToolkit().getScreenInsets(gc);
        int left = screen.x + screenInsets.left;
        int usable = screen.width - screenInsets.left - screenInsets.right;
        int width = Math.min(needed, usable);
        // keep the dialog on the screen
        int x = Math.max(left, Math.min(getX(), left + usable - width));
        setBounds(x, getY(), width, getHeight());
        validate();
    }
    
    public void setText(String text) {
        setText(text, "");
    }

    /**
     * Shows a text, e.g. the content of a file, with a status below it (e.g. the number of lines).
     *
     * @param text the text
     * @param status the status, an empty string shows none
     */
    public void setText(String text, String status) {
        ensureMonospacedFont();
        statusLabel.setText(status);
        helpTextArea.setText(text);
        helpTextArea.setCaretPosition(0);
    }

    /**
     * The texts are preformatted (manpage, hex dump), so they need a monospaced font. FlatLaf
     * gets one by the style that is set in the constructor; other look and feels (Nimbus, the
     * system one) don't know that style, so their font is replaced if it isn't monospaced.
     */
    private void ensureMonospacedFont() {
        java.awt.Font font = helpTextArea.getFont();
        java.awt.FontMetrics fm = helpTextArea.getFontMetrics(font);
        if (fm.charWidth('i') != fm.charWidth('W')) {
            helpTextArea.setFont(new java.awt.Font(java.awt.Font.MONOSPACED, java.awt.Font.PLAIN, font.getSize()));
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel helpPanel;
    private javax.swing.JScrollPane helpScrollPane;
    private javax.swing.JTextArea helpTextArea;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
